import { library } from '@fortawesome/fontawesome-svg-core';
import { faApple, faGithub } from '@fortawesome/free-brands-svg-icons';
import {
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faArrowUpRightFromSquare,
    faBook,
    faBriefcase,
    faBuilding,
    faCalendar,
    faChartSimple,
    faCheck,
    faChevronDown,
    faChevronRight,
    faCircleCheck,
    faCircleHalfStroke,
    faClock,
    faDesktop,
    faDownload,
    faEllipsis,
    faFileImport,
    faFileInvoice,
    faGear,
    faGlobe,
    faHouse,
    faKey,
    faMagnifyingGlass,
    faMinus,
    faMoon,
    faPalette,
    faPlug,
    faPlus,
    faRightFromBracket,
    faRobot,
    faShield,
    faSidebar,
    faStopwatch,
    faSun,
    faTimer,
    faUser,
    faXmark,
} from '@fortawesome/pro-regular-svg-icons';
import {
    faPlay as faPlaySolid,
    faSquare as faSquareSolid,
    faStop as faStopSolid,
} from '@fortawesome/pro-solid-svg-icons';

/**
 * Every Font Awesome Pro icon the app renders through `<FaIcon>`. Icons
 * are registered by name once here so a template can ask for `icon="clock"`
 * and tree-shaking still drops the thousands we never use. Regular is the
 * house weight; solid is reserved for small filled glyphs (stop, play).
 * Add an icon here before using it, otherwise `<FaIcon>` renders nothing.
 */
library.add(
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faApple,
    faArrowUpRightFromSquare,
    faBook,
    faBriefcase,
    faBuilding,
    faCalendar,
    faChartSimple,
    faCheck,
    faChevronDown,
    faChevronRight,
    faCircleCheck,
    faCircleHalfStroke,
    faClock,
    faDesktop,
    faDownload,
    faEllipsis,
    faFileImport,
    faFileInvoice,
    faGear,
    faGlobe,
    faGithub,
    faHouse,
    faKey,
    faMagnifyingGlass,
    faMinus,
    faMoon,
    faPalette,
    faPlaySolid,
    faPlug,
    faPlus,
    faRightFromBracket,
    faRobot,
    faShield,
    faSidebar,
    faSquareSolid,
    faStopSolid,
    faStopwatch,
    faSun,
    faTimer,
    faUser,
    faXmark,
);
